import type { WeatherIcon, WeatherSymbol } from '../../../shared/weather.ts';

const one = (symbol: WeatherSymbol): WeatherIcon => ({ symbol });
const sometimes = (symbol: WeatherSymbol, next: WeatherSymbol): WeatherIcon => ({
  symbol,
  change: 'sometimes',
  next,
});
const later = (symbol: WeatherSymbol, next: WeatherSymbol): WeatherIcon => ({
  symbol,
  change: 'later',
  next,
});

/**
 * 気象庁の天気コード（予報の `weatherCodes`）→ [アイコン, 天気の名前]。
 *
 * 名前は気象庁の予報ページが持つ表（`Forecast.Const.TELOPS`）を写したもの。アイコンは名前を
 * 「最初の天気」「変わり方」「次の天気」に分けたもので、気象庁の予報のアイコンと同じく、
 * 「時々」「一時」を `/`、「後」「から」を `→` で表す。
 * - 「朝の内」「夕方」「朝夕」など時間帯の付いた「一時」は、いつ降るかは名前に任せて sometimes にする。
 * - 「山沿い」「海上海岸は」の付く天気は東京の平地の天気ではないので、アイコンには出さない（名前には残る）。
 * - 「大雨」「暴風」「強く降る」などの強さと、雷を伴う雪は、部品を増やさず雨・雪で表す（名前には残る）。
 * - 「雨か雪」「雪か雨」「みぞれ」は、どちらが先かを区別せず sleet にする。
 * WHY NOT 名前の文字列から実行時に組み立てる: 例外（山沿い・時間帯・強さ）の規則が名前の書き方に
 * 依存して壊れやすく、表として並べたほうが 1 行ずつ確かめられる。
 * WHY NOT 実行時に気象庁の表を読む: 表は予報ページの JS に埋め込まれていて、取り出す口が公開されていない。
 */
export const TELOPS: Record<string, readonly [icon: WeatherIcon, label: string]> = {
  100: [one('sun'), '晴'],
  101: [sometimes('sun', 'cloud'), '晴時々曇'],
  102: [sometimes('sun', 'rain'), '晴一時雨'],
  103: [sometimes('sun', 'rain'), '晴時々雨'],
  104: [sometimes('sun', 'snow'), '晴一時雪'],
  105: [sometimes('sun', 'snow'), '晴時々雪'],
  106: [sometimes('sun', 'sleet'), '晴一時雨か雪'],
  107: [sometimes('sun', 'sleet'), '晴時々雨か雪'],
  108: [sometimes('sun', 'thunder'), '晴一時雨か雷雨'],
  110: [later('sun', 'cloud'), '晴後時々曇'],
  111: [later('sun', 'cloud'), '晴後曇'],
  112: [later('sun', 'rain'), '晴後一時雨'],
  113: [later('sun', 'rain'), '晴後時々雨'],
  114: [later('sun', 'rain'), '晴後雨'],
  115: [later('sun', 'snow'), '晴後一時雪'],
  116: [later('sun', 'snow'), '晴後時々雪'],
  117: [later('sun', 'snow'), '晴後雪'],
  118: [later('sun', 'sleet'), '晴後雨か雪'],
  119: [later('sun', 'thunder'), '晴後雨か雷雨'],
  120: [sometimes('sun', 'rain'), '晴朝夕一時雨'],
  121: [sometimes('sun', 'rain'), '晴朝の内一時雨'],
  122: [sometimes('sun', 'rain'), '晴夕方一時雨'],
  123: [one('sun'), '晴山沿い雷雨'],
  124: [one('sun'), '晴山沿い雪'],
  125: [later('sun', 'thunder'), '晴午後は雷雨'],
  126: [later('sun', 'rain'), '晴昼頃から雨'],
  127: [later('sun', 'rain'), '晴夕方から雨'],
  128: [later('sun', 'rain'), '晴夜は雨'],
  130: [later('fog', 'sun'), '朝の内霧後晴'],
  131: [sometimes('sun', 'fog'), '晴明け方霧'],
  132: [sometimes('sun', 'cloud'), '晴朝夕曇'],
  140: [sometimes('sun', 'thunder'), '晴時々雨で雷を伴う'],
  160: [sometimes('sun', 'sleet'), '晴一時雪か雨'],
  170: [sometimes('sun', 'sleet'), '晴時々雪か雨'],
  181: [later('sun', 'sleet'), '晴後雪か雨'],
  200: [one('cloud'), '曇'],
  201: [sometimes('cloud', 'sun'), '曇時々晴'],
  202: [sometimes('cloud', 'rain'), '曇一時雨'],
  203: [sometimes('cloud', 'rain'), '曇時々雨'],
  204: [sometimes('cloud', 'snow'), '曇一時雪'],
  205: [sometimes('cloud', 'snow'), '曇時々雪'],
  206: [sometimes('cloud', 'sleet'), '曇一時雨か雪'],
  207: [sometimes('cloud', 'sleet'), '曇時々雨か雪'],
  208: [sometimes('cloud', 'thunder'), '曇一時雨か雷雨'],
  209: [one('fog'), '霧'],
  210: [later('cloud', 'sun'), '曇後時々晴'],
  211: [later('cloud', 'sun'), '曇後晴'],
  212: [later('cloud', 'rain'), '曇後一時雨'],
  213: [later('cloud', 'rain'), '曇後時々雨'],
  214: [later('cloud', 'rain'), '曇後雨'],
  215: [later('cloud', 'snow'), '曇後一時雪'],
  216: [later('cloud', 'snow'), '曇後時々雪'],
  217: [later('cloud', 'snow'), '曇後雪'],
  218: [later('cloud', 'sleet'), '曇後雨か雪'],
  219: [later('cloud', 'thunder'), '曇後雨か雷雨'],
  220: [sometimes('cloud', 'rain'), '曇朝夕一時雨'],
  221: [sometimes('cloud', 'rain'), '曇朝の内一時雨'],
  222: [sometimes('cloud', 'rain'), '曇夕方一時雨'],
  223: [sometimes('cloud', 'sun'), '曇日中時々晴'],
  224: [later('cloud', 'rain'), '曇昼頃から雨'],
  225: [later('cloud', 'rain'), '曇夕方から雨'],
  226: [later('cloud', 'rain'), '曇夜は雨'],
  228: [later('cloud', 'snow'), '曇昼頃から雪'],
  229: [later('cloud', 'snow'), '曇夕方から雪'],
  230: [later('cloud', 'snow'), '曇夜は雪'],
  231: [one('cloud'), '曇海上海岸は霧か霧雨'],
  240: [sometimes('cloud', 'thunder'), '曇時々雨で雷を伴う'],
  250: [sometimes('cloud', 'snow'), '曇時々雪で雷を伴う'],
  260: [sometimes('cloud', 'sleet'), '曇一時雪か雨'],
  270: [sometimes('cloud', 'sleet'), '曇時々雪か雨'],
  281: [later('cloud', 'sleet'), '曇後雪か雨'],
  300: [one('rain'), '雨'],
  301: [sometimes('rain', 'sun'), '雨時々晴'],
  302: [sometimes('rain', 'cloud'), '雨時々止む'],
  303: [sometimes('rain', 'snow'), '雨時々雪'],
  304: [one('sleet'), '雨か雪'],
  306: [one('rain'), '大雨'],
  308: [one('rain'), '雨で暴風を伴う'],
  309: [sometimes('rain', 'snow'), '雨一時雪'],
  311: [later('rain', 'sun'), '雨後晴'],
  313: [later('rain', 'cloud'), '雨後曇'],
  314: [later('rain', 'snow'), '雨後時々雪'],
  315: [later('rain', 'snow'), '雨後雪'],
  316: [later('sleet', 'sun'), '雨か雪後晴'],
  317: [later('sleet', 'cloud'), '雨か雪後曇'],
  320: [later('rain', 'sun'), '朝の内雨後晴'],
  321: [later('rain', 'cloud'), '朝の内雨後曇'],
  322: [sometimes('rain', 'snow'), '雨朝晩一時雪'],
  323: [later('rain', 'sun'), '雨昼頃から晴'],
  324: [later('rain', 'sun'), '雨夕方から晴'],
  325: [later('rain', 'sun'), '雨夜は晴'],
  326: [later('rain', 'snow'), '雨夕方から雪'],
  327: [later('rain', 'snow'), '雨夜は雪'],
  328: [one('rain'), '雨一時強く降る'],
  329: [sometimes('rain', 'sleet'), '雨一時みぞれ'],
  340: [one('sleet'), '雪か雨'],
  350: [one('thunder'), '雨で雷を伴う'],
  361: [later('sleet', 'sun'), '雪か雨後晴'],
  371: [later('sleet', 'cloud'), '雪か雨後曇'],
  400: [one('snow'), '雪'],
  401: [sometimes('snow', 'sun'), '雪時々晴'],
  402: [sometimes('snow', 'cloud'), '雪時々止む'],
  403: [sometimes('snow', 'rain'), '雪時々雨'],
  405: [one('snow'), '大雪'],
  406: [one('snow'), '風雪強い'],
  407: [one('snow'), '暴風雪'],
  409: [sometimes('snow', 'rain'), '雪一時雨'],
  411: [later('snow', 'sun'), '雪後晴'],
  413: [later('snow', 'cloud'), '雪後曇'],
  414: [later('snow', 'rain'), '雪後雨'],
  420: [later('snow', 'sun'), '朝の内雪後晴'],
  421: [later('snow', 'cloud'), '朝の内雪後曇'],
  422: [later('snow', 'rain'), '雪昼頃から雨'],
  423: [later('snow', 'rain'), '雪夕方から雨'],
  425: [one('snow'), '雪一時強く降る'],
  426: [later('snow', 'sleet'), '雪後みぞれ'],
  427: [sometimes('snow', 'sleet'), '雪一時みぞれ'],
  450: [one('snow'), '雪で雷を伴う'],
};
