/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedLemonRouteImport } from './routes/_authenticated/lemon'
import { Route as AuthenticatedMoneyRouteImport } from './routes/_authenticated/money'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedWeatherRouteImport } from './routes/_authenticated/weather'
import { Route as AuthenticatedAdminMoneyRulesRouteImport } from './routes/_authenticated/admin.money-rules'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLemonRoute = AuthenticatedLemonRouteImport.update({
  id: '/lemon',
  path: '/lemon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMoneyRoute = AuthenticatedMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWeatherRoute = AuthenticatedWeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMoneyRulesRoute =
  AuthenticatedAdminMoneyRulesRouteImport.update({
    id: '/admin/money-rules',
    path: '/admin/money-rules',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/lemon': typeof AuthenticatedLemonRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/admin/money-rules': typeof AuthenticatedAdminMoneyRulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/lemon': typeof AuthenticatedLemonRoute
  '/money': typeof AuthenticatedMoneyRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/weather': typeof AuthenticatedWeatherRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/money-rules': typeof AuthenticatedAdminMoneyRulesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/consent': typeof ConsentRoute
  '/login': typeof LoginRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/lemon': typeof AuthenticatedLemonRoute
  '/_authenticated/money': typeof AuthenticatedMoneyRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/weather': typeof AuthenticatedWeatherRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/money-rules': typeof AuthenticatedAdminMoneyRulesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/login'
    | '/calendar'
    | '/lemon'
    | '/money'
    | '/settings'
    | '/weather'
    | '/admin/money-rules'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/consent'
    | '/login'
    | '/calendar'
    | '/lemon'
    | '/money'
    | '/settings'
    | '/weather'
    | '/'
    | '/admin/money-rules'
    | '/admin/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/consent'
    | '/login'
    | '/_authenticated/calendar'
    | '/_authenticated/lemon'
    | '/_authenticated/money'
    | '/_authenticated/settings'
    | '/_authenticated/weather'
    | '/_authenticated/'
    | '/_authenticated/admin/money-rules'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ConsentRoute: typeof ConsentRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lemon': {
      id: '/_authenticated/lemon'
      path: '/lemon'
      fullPath: '/lemon'
      preLoaderRoute: typeof AuthenticatedLemonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/money': {
      id: '/_authenticated/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof AuthenticatedMoneyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/weather': {
      id: '/_authenticated/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof AuthenticatedWeatherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/money-rules': {
      id: '/_authenticated/admin/money-rules'
      path: '/admin/money-rules'
      fullPath: '/admin/money-rules'
      preLoaderRoute: typeof AuthenticatedAdminMoneyRulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedLemonRoute: typeof AuthenticatedLemonRoute
  AuthenticatedMoneyRoute: typeof AuthenticatedMoneyRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWeatherRoute: typeof AuthenticatedWeatherRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAdminMoneyRulesRoute: typeof AuthenticatedAdminMoneyRulesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedLemonRoute: AuthenticatedLemonRoute,
  AuthenticatedMoneyRoute: AuthenticatedMoneyRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWeatherRoute: AuthenticatedWeatherRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAdminMoneyRulesRoute: AuthenticatedAdminMoneyRulesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ConsentRoute: ConsentRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
